---
include:
  - board: seeeduino_xiao_ble
    shield: mulkey_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart mulkey_US
    artifact-name: mulkey_L_US

  - board: seeeduino_xiao_ble
    shield: mulkey_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart mulkey_US
    artifact-name: mulkey_R_US

  - board: seeeduino_xiao_ble
    shield: mulkey_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart mulkey_JIS
    artifact-name: mulkey_L_JIS

  - board: seeeduino_xiao_ble
    shield: mulkey_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart mulkey_JIS
    artifact-name: mulkey_R_JIS

  - board: seeeduino_xiao_ble
    shield: settings_reset
    
